# Generated by Django 3.2.6 on 2021-08-30 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P_claves',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='autor',
        ),
    ]
